[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[workspace]
members = [
    "eosio-core",
    "eosio-core-derive",
    "eosio-core-macros",
    "eosio-core-macros-internal",
]
